[[redirects]]
from = “/*”
to = “/index.html”
status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy =  "no-referrer"
    Content-Security-Policy = "default-src https: 'unsafe-eval' 'unsafe-inline'"
    Permissions-Policy = "geolocation=(self 'https://perseep-frontend.herokuapp.com/'), microphone=()"
